services:
  - type: web
    env: node
    name: fh-prod-backend1
    repo: https://github.com/iuldia/shopping-app
    buildFilter:
      paths:
        - shopping-lists/**
    buildCommand: curl -fsSL https://deno.land/x/install/install.sh | sh
    startCommand: export PATH="$DENO_INSTALL/bin:$PATH" && cd shopping-lists && deno run --unstable --allow-net --allow-read --allow-write --allow-env app.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fh-prod-db1
          property: connectionString
      - key: DENO_INSTALL
        value: /opt/render/project/.deno

databases:
  - name: fh-prod-db1
